---
  - name: Configure for all hosts
    hosts: backup client
    become: yes


    tasks:    
    - name: Instal epel-release
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Instal borgbackup
      ansible.builtin.yum:
        name: borgbackup
        state: latest
    
  - name: Configure for backup
    hosts: backup
    become: yes
    vars:
      pd: Qwe12345


    tasks:
    - name: Create user borg
      ansible.builtin.user:
        name: borg
        generate_ssh_key: true
        password: "{{ pd | password_hash('sha512') }}" 
        state: present
        
    - name: create /var/backup
      ansible.builtin.file:
        path: /var/backup
        state: directory
        owner: borg
        group: borg
        
        
  
    - name: create /home/borg/.ssh/authorized_keys
      ansible.builtin.file:
        path: /home/borg/.ssh/authorized_keys
        owner: borg
        group: borg
        mode: '700'
        state: directory
    - name: create ext4 FS on /dev/sdb
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sda
    - name: mount
      ansible.posix.mount:     
        path: /var/backup
        src: /dev/sda
        fstype: ext4
        state: mounted
  